In [1]:
 pip install pandas

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import pandas as pd
from datetime import datetime

In [3]:
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

In [4]:
all_records = []
start_year = datetime.now().year - 5
end_year = datetime.now().year

In [5]:
for year in range(start_year,end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"
            
        print(start_date, "→", end_date)  # Demo only

2021-01-01 → 2021-02-01
2021-02-01 → 2021-03-01
2021-03-01 → 2021-04-01
2021-04-01 → 2021-05-01
2021-05-01 → 2021-06-01
2021-06-01 → 2021-07-01
2021-07-01 → 2021-08-01
2021-08-01 → 2021-09-01
2021-09-01 → 2021-10-01
2021-10-01 → 2021-11-01
2021-11-01 → 2021-12-01
2021-12-01 → 2022-01-01
2022-01-01 → 2022-02-01
2022-02-01 → 2022-03-01
2022-03-01 → 2022-04-01
2022-04-01 → 2022-05-01
2022-05-01 → 2022-06-01
2022-06-01 → 2022-07-01
2022-07-01 → 2022-08-01
2022-08-01 → 2022-09-01
2022-09-01 → 2022-10-01
2022-10-01 → 2022-11-01
2022-11-01 → 2022-12-01
2022-12-01 → 2023-01-01
2023-01-01 → 2023-02-01
2023-02-01 → 2023-03-01
2023-03-01 → 2023-04-01
2023-04-01 → 2023-05-01
2023-05-01 → 2023-06-01
2023-06-01 → 2023-07-01
2023-07-01 → 2023-08-01
2023-08-01 → 2023-09-01
2023-09-01 → 2023-10-01
2023-10-01 → 2023-11-01
2023-11-01 → 2023-12-01
2023-12-01 → 2024-01-01
2024-01-01 → 2024-02-01
2024-02-01 → 2024-03-01
2024-03-01 → 2024-04-01
2024-04-01 → 2024-05-01
2024-05-01 → 2024-06-01
2024-06-01 → 2024-07-01
2024-07-01 → 2024-08-01
2024-08-01 → 2024-09-01
2024-09-01 → 2024-10-01
2024-10-01 → 2024-11-01
2024-11-01 → 2024-12-01
2024-12-01 → 2025-01-01
2025-01-01 → 2025-02-01
2025-02-01 → 2025-03-01
2025-03-01 → 2025-04-01
2025-04-01 → 2025-05-01
2025-05-01 → 2025-06-01
2025-06-01 → 2025-07-01
2025-07-01 → 2025-08-01
2025-08-01 → 2025-09-01
2025-09-01 → 2025-10-01
2025-10-01 → 2025-11-01
2025-11-01 → 2025-12-01
2025-12-01 → 2026-01-01
2026-01-01 → 2026-02-01
2026-02-01 → 2026-03-01
2026-03-01 → 2026-04-01
2026-04-01 → 2026-05-01
2026-05-01 → 2026-06-01
2026-06-01 → 2026-07-01
2026-07-01 → 2026-08-01
2026-08-01 → 2026-09-01
2026-09-01 → 2026-10-01
2026-10-01 → 2026-11-01
2026-11-01 → 2026-12-01
2026-12-01 → 2027-01-01

In [6]:
  params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

print(params)

{'format': 'geojson', 'starttime': '2026-12-01', 'endtime': '2027-01-01', 'minmagnitude': 3}

In [7]:
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

In [8]:
response = requests.get(url, params=params)

if response.status_code != 200:
    print("Request failed:", response.text[:200])
else:
    print("Success!")

Success!

In [9]:
print(response)

<Response [200]>

print(data)

In [10]:
import requests
import pandas as pd

# Empty list to store earthquake records
all_records = []

# API URL
url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

# Year range
start_year = 2020
end_year = 2025

# Loop through years
for year in range(start_year, end_year + 1):

    # Loop through months
    for month in range(1, 13):

        # Create start date
        start_date = f"{year}-{month:02d}-01"

        # Create end date
        if month == 12:
            end_date = f"{year + 1}-01-01"
        else:
            end_date = f"{year}-{month + 1:02d}-01"

        # API parameters
        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        # Send API request
        response = requests.get(url, params=params)

        # Check request status
        if response.status_code != 200:
            print(f"Failed for {start_date}: {response.text[:200]}")
            continue

        # Convert response into JSON
        try:
            data = response.json()

        except Exception as e:
            print(f"JSON error for {start_date}: {e}")
            continue

        # Extract earthquake records
        for f in data["features"]:

            # Earthquake properties
            p = f["properties"]

            # Coordinates [longitude, latitude, depth]
            g = f["geometry"]["coordinates"]

            # Store earthquake data
            all_records.append({

                "id": f.get("id"),

                "time": pd.to_datetime(
                    p.get("time"), unit="ms"
                ),

                "updated": pd.to_datetime(
                    p.get("updated"), unit="ms"
                ),

                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,

                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place": p.get("place"),
                "status": p.get("status"),
                "tsunami": p.get("tsunami"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "magError": p.get("magError"),
                "depthError": p.get("depthError"),
                "magNst": p.get("magNst"),
                "locationSource": p.get("locationSource"),
                "magSource": p.get("magSource"),
                "types": p.get("types"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "type": p.get("type")

            })

# Convert list into DataFrame
df = pd.DataFrame(all_records)

In [13]:
print("Rows:", df.shape[0])

Rows: 124959

In [14]:
print("Columns:", df.shape[1])

Columns: 26

In [15]:
print(df.head())

             id                    time                 updated  latitude  \
0  pr2020031037 2020-01-31 23:42:29.870 2020-04-18 22:10:07.040   18.8990
1    us60007lub 2020-01-31 23:32:51.609 2020-04-18 22:10:07.040   38.4961
2    us60007lul 2020-01-31 23:06:11.255 2020-04-18 22:10:07.040  -12.2747
3    us60007lsc 2020-01-31 22:10:55.844 2025-12-22 18:27:38.231   -6.4065
4    us60007lq0 2020-01-31 21:05:32.436 2020-04-18 22:10:06.040   41.4433

   longitude  depth_km  mag magType  \
0   -67.8238     10.00  3.2      md
1    39.3382     10.00  4.7     mwr
2   -76.6148     75.51  4.7      mb
3   129.1523    221.39  5.0     mww
4    19.4321     10.00  4.4      mb

                                         place    status  ...    gap  \
0  70 km ENE of Punta Cana, Dominican Republic  reviewed  ...  321.0
1                  6 km NNE of Sivrice, Turkey  reviewed  ...   34.0
2               21 km ENE of San Bartolo, Peru  reviewed  ...  167.0
3                                    Banda Sea  reviewed  ...   28.0
4                   13 km N of Durrës, Albania  reviewed  ...   51.0

   magError depthError  magNst  locationSource  magSource  \
0      None       None    None            None       None
1      None       None    None            None       None
2      None       None    None            None       None
3      None       None    None            None       None
4      None       None    None            None       None

                                    types                           ids  \
0                ,dyfi,origin,phase-data,     ,pr2020031037,us60007lv7,
1       ,moment-tensor,origin,phase-data,                  ,us60007lub,
2                ,dyfi,origin,phase-data,                  ,us60007lul,
3  ,dyfi,moment-tensor,origin,phase-data,  ,us60007lsc,iscgem617252948,
4                     ,origin,phase-data,                  ,us60007lq0,

       sources        type
0      ,pr,us,  earthquake
1         ,us,  earthquake
2         ,us,  earthquake
3  ,us,iscgem,  earthquake
4         ,us,  earthquake

[5 rows x 26 columns]

In [16]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'magError', 'depthError', 'magNst', 'locationSource',
       'magSource', 'types', 'ids', 'sources', 'type'],
      dtype='object')

In [17]:
# Save DataFrame into CSV file
df.to_csv("earthquake_data.csv", index=False)

print("CSV file saved successfully")

CSV file saved successfully

In [18]:
import pandas as pd

In [19]:
# Load CSV file
df = pd.read_csv("earthquake_data.csv")

In [22]:
# Convert datetime columns
df["time"] = pd.to_datetime(df["time"])
df["updated"] = pd.to_datetime(df["updated"])

In [21]:
# Display dataset information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124959 entries, 0 to 124958
Data columns (total 26 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              124959 non-null  object
 1   time            124959 non-null  datetime64[ns]
 2   updated         124959 non-null  datetime64[ns]
 3   latitude        124959 non-null  float64
 4   longitude       124959 non-null  float64
 5   depth_km        124959 non-null  float64
 6   mag             124959 non-null  float64
 7   magType         124958 non-null  object
 8   place           124959 non-null  object
 9   status          124959 non-null  object
 10  tsunami         124959 non-null  int64
 11  sig             124959 non-null  int64
 12  net             124959 non-null  object
 13  nst             80005 non-null   float64
 14  dmin            120294 non-null  float64
 15  rms             124924 non-null  float64
 16  gap             121304 non-null  float64
 17  magError        0 non-null       float64
 18  depthError      0 non-null       float64
 19  magNst          0 non-null       float64
 20  locationSource  0 non-null       float64
 21  magSource       0 non-null       float64
 22  types           124959 non-null  object
 23  ids             124959 non-null  object
 24  sources         124959 non-null  object
 25  type            124959 non-null  object
dtypes: datetime64[ns](2), float64(13), int64(2), object(9)
memory usage: 24.8+ MB
None

In [23]:
# Display first 5 rows
print(df.head())

             id                    time                 updated  latitude  \
0  pr2020031037 2020-01-31 23:42:29.870 2020-04-18 22:10:07.040   18.8990
1    us60007lub 2020-01-31 23:32:51.609 2020-04-18 22:10:07.040   38.4961
2    us60007lul 2020-01-31 23:06:11.255 2020-04-18 22:10:07.040  -12.2747
3    us60007lsc 2020-01-31 22:10:55.844 2025-12-22 18:27:38.231   -6.4065
4    us60007lq0 2020-01-31 21:05:32.436 2020-04-18 22:10:06.040   41.4433

   longitude  depth_km  mag magType  \
0   -67.8238     10.00  3.2      md
1    39.3382     10.00  4.7     mwr
2   -76.6148     75.51  4.7      mb
3   129.1523    221.39  5.0     mww
4    19.4321     10.00  4.4      mb

                                         place    status  ...    gap  \
0  70 km ENE of Punta Cana, Dominican Republic  reviewed  ...  321.0
1                  6 km NNE of Sivrice, Turkey  reviewed  ...   34.0
2               21 km ENE of San Bartolo, Peru  reviewed  ...  167.0
3                                    Banda Sea  reviewed  ...   28.0
4                   13 km N of Durrës, Albania  reviewed  ...   51.0

   magError depthError  magNst  locationSource  magSource  \
0       NaN        NaN     NaN             NaN        NaN
1       NaN        NaN     NaN             NaN        NaN
2       NaN        NaN     NaN             NaN        NaN
3       NaN        NaN     NaN             NaN        NaN
4       NaN        NaN     NaN             NaN        NaN

                                    types                           ids  \
0                ,dyfi,origin,phase-data,     ,pr2020031037,us60007lv7,
1       ,moment-tensor,origin,phase-data,                  ,us60007lub,
2                ,dyfi,origin,phase-data,                  ,us60007lul,
3  ,dyfi,moment-tensor,origin,phase-data,  ,us60007lsc,iscgem617252948,
4                     ,origin,phase-data,                  ,us60007lq0,

       sources        type
0      ,pr,us,  earthquake
1         ,us,  earthquake
2         ,us,  earthquake
3  ,us,iscgem,  earthquake
4         ,us,  earthquake

[5 rows x 26 columns]

In [26]:
import pandas as pd

# Extract country/region from place column using Regex
df["country"] = df["place"].str.extract(r",\s*([^,]+)$")

# Convert alert column to lowercase (if column exists)
if "alert" in df.columns:
    df["alert"] = df["alert"].str.lower()

# List of text columns to clean
text_columns = [
    "magType",
    "status",
    "type",
    "net",
    "sources",
    "types"
]

# Clean string columns
for col in text_columns:

    # Check whether column exists
    if col in df.columns:

        # Convert values to string
        df[col] = df[col].astype(str)

        # Remove extra spaces
        df[col] = df[col].str.strip()

        # Convert text to lowercase
        df[col] = df[col].str.lower()

In [27]:
# Display cleaned dataset
print(df.head())

             id                    time                 updated  latitude  \
0  pr2020031037 2020-01-31 23:42:29.870 2020-04-18 22:10:07.040   18.8990
1    us60007lub 2020-01-31 23:32:51.609 2020-04-18 22:10:07.040   38.4961
2    us60007lul 2020-01-31 23:06:11.255 2020-04-18 22:10:07.040  -12.2747
3    us60007lsc 2020-01-31 22:10:55.844 2025-12-22 18:27:38.231   -6.4065
4    us60007lq0 2020-01-31 21:05:32.436 2020-04-18 22:10:06.040   41.4433

   longitude  depth_km  mag magType  \
0   -67.8238     10.00  3.2      md
1    39.3382     10.00  4.7     mwr
2   -76.6148     75.51  4.7      mb
3   129.1523    221.39  5.0     mww
4    19.4321     10.00  4.4      mb

                                         place    status  ...  magError  \
0  70 km ENE of Punta Cana, Dominican Republic  reviewed  ...       NaN
1                  6 km NNE of Sivrice, Turkey  reviewed  ...       NaN
2               21 km ENE of San Bartolo, Peru  reviewed  ...       NaN
3                                    Banda Sea  reviewed  ...       NaN
4                   13 km N of Durrës, Albania  reviewed  ...       NaN

   depthError magNst  locationSource  magSource  \
0         NaN    NaN             NaN        NaN
1         NaN    NaN             NaN        NaN
2         NaN    NaN             NaN        NaN
3         NaN    NaN             NaN        NaN
4         NaN    NaN             NaN        NaN

                                    types                           ids  \
0                ,dyfi,origin,phase-data,     ,pr2020031037,us60007lv7,
1       ,moment-tensor,origin,phase-data,                  ,us60007lub,
2                ,dyfi,origin,phase-data,                  ,us60007lul,
3  ,dyfi,moment-tensor,origin,phase-data,  ,us60007lsc,iscgem617252948,
4                     ,origin,phase-data,                  ,us60007lq0,

       sources        type             country
0      ,pr,us,  earthquake  Dominican Republic
1         ,us,  earthquake              Turkey
2         ,us,  earthquake                Peru
3  ,us,iscgem,  earthquake                 NaN
4         ,us,  earthquake             Albania

[5 rows x 27 columns]

In [28]:
import pandas as pd

# List of numeric columns
numeric_columns = [
    "mag",
    "depth_km",
    "nst",
    "dmin",
    "rms",
    "gap",
    "magError",
    "depthError",
    "magNst",
    "sig"
]

# Convert columns to numeric datatype
for col in numeric_columns:

    # Check whether column exists
    if col in df.columns:

        # Convert values into numeric format
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )

        # Fill missing values with median
        df[col] = df[col].fillna(
            df[col].median()
        )

# Display cleaned numeric data
print(df[numeric_columns].head())

   mag  depth_km   nst    dmin   rms    gap  magError  depthError  magNst  sig
0  3.2     10.00  10.0  0.6193  0.98  321.0       NaN         NaN     NaN  158
1  4.7     10.00  31.0  0.9840  0.96   34.0       NaN         NaN     NaN  340
2  4.7     75.51  31.0  0.3610  0.63  167.0       NaN         NaN     NaN  348
3  5.0    221.39  31.0  2.6430  0.72   28.0       NaN         NaN     NaN  385
4  4.4     10.00  31.0  0.9930  0.83   51.0       NaN         NaN     NaN  298

In [29]:
import pandas as pd

# Extract date-related columns from time
df["year"] = df["time"].dt.year

df["month"] = df["time"].dt.month

df["day"] = df["time"].dt.day

df["day_of_week"] = df["time"].dt.day_name()

# Create shallow/deep earthquake flag
df["depth_category"] = df["depth_km"].apply(
    lambda x: "shallow" if x < 70 else "deep"
)

# Create earthquake strength category
def classify_magnitude(mag):

    if mag >= 7:
        return "destructive"

    elif mag >= 5:
        return "strong"

    else:
        return "moderate"

# Apply magnitude classification
df["magnitude_category"] = df["mag"].apply(
    classify_magnitude
)

# Display updated dataset
print(df.head())

             id                    time                 updated  latitude  \
0  pr2020031037 2020-01-31 23:42:29.870 2020-04-18 22:10:07.040   18.8990
1    us60007lub 2020-01-31 23:32:51.609 2020-04-18 22:10:07.040   38.4961
2    us60007lul 2020-01-31 23:06:11.255 2020-04-18 22:10:07.040  -12.2747
3    us60007lsc 2020-01-31 22:10:55.844 2025-12-22 18:27:38.231   -6.4065
4    us60007lq0 2020-01-31 21:05:32.436 2020-04-18 22:10:06.040   41.4433

   longitude  depth_km  mag magType  \
0   -67.8238     10.00  3.2      md
1    39.3382     10.00  4.7     mwr
2   -76.6148     75.51  4.7      mb
3   129.1523    221.39  5.0     mww
4    19.4321     10.00  4.4      mb

                                         place    status  ...  \
0  70 km ENE of Punta Cana, Dominican Republic  reviewed  ...
1                  6 km NNE of Sivrice, Turkey  reviewed  ...
2               21 km ENE of San Bartolo, Peru  reviewed  ...
3                                    Banda Sea  reviewed  ...
4                   13 km N of Durrës, Albania  reviewed  ...

                            ids      sources        type             country  \
0     ,pr2020031037,us60007lv7,      ,pr,us,  earthquake  Dominican Republic
1                  ,us60007lub,         ,us,  earthquake              Turkey
2                  ,us60007lul,         ,us,  earthquake                Peru
3  ,us60007lsc,iscgem617252948,  ,us,iscgem,  earthquake                 NaN
4                  ,us60007lq0,         ,us,  earthquake             Albania

   year  month  day  day_of_week  depth_category  magnitude_category
0  2020      1   31       Friday         shallow            moderate
1  2020      1   31       Friday         shallow            moderate
2  2020      1   31       Friday            deep            moderate
3  2020      1   31       Friday            deep              strong
4  2020      1   31       Friday         shallow            moderate

[5 rows x 33 columns]

In [30]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'magError', 'depthError', 'magNst', 'locationSource',
       'magSource', 'types', 'ids', 'sources', 'type', 'country', 'year',
       'month', 'day', 'day_of_week', 'depth_category', 'magnitude_category'],
      dtype='object')

In [31]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,ids,sources,type,country,year,month,day,day_of_week,depth_category,magnitude_category
0,pr2020031037,2020-01-31 23:42:29.870,2020-04-18 22:10:07.040,18.8990,-67.8238,10.00,3.2,md,"70 km ENE of Punta Cana, Dominican Republic",reviewed,...,",pr2020031037,us60007lv7,",",pr,us,",earthquake,Dominican Republic,2020,1,31,Friday,shallow,moderate
1,us60007lub,2020-01-31 23:32:51.609,2020-04-18 22:10:07.040,38.4961,39.3382,10.00,4.7,mwr,"6 km NNE of Sivrice, Turkey",reviewed,...,",us60007lub,",",us,",earthquake,Turkey,2020,1,31,Friday,shallow,moderate
2,us60007lul,2020-01-31 23:06:11.255,2020-04-18 22:10:07.040,-12.2747,-76.6148,75.51,4.7,mb,"21 km ENE of San Bartolo, Peru",reviewed,...,",us60007lul,",",us,",earthquake,Peru,2020,1,31,Friday,deep,moderate
3,us60007lsc,2020-01-31 22:10:55.844,2025-12-22 18:27:38.231,-6.4065,129.1523,221.39,5.0,mww,Banda Sea,reviewed,...,",us60007lsc,iscgem617252948,",",us,iscgem,",earthquake,NaN,2020,1,31,Friday,deep,strong
4,us60007lq0,2020-01-31 21:05:32.436,2020-04-18 22:10:06.040,41.4433,19.4321,10.00,4.4,mb,"13 km N of Durrës, Albania",reviewed,...,",us60007lq0,",",us,",earthquake,Albania,2020,1,31,Friday,shallow,moderate

In [32]:
df.tail()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,ids,sources,type,country,year,month,day,day_of_week,depth_category,magnitude_category
124954,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,"60 km SSE of Halibut Cove, Alaska",reviewed,...,",us7000ret4,ak2025xpgfse,",",us,ak,",earthquake,Alaska,2025,12,1,Monday,shallow,moderate
124955,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,"53 km E of Baculin, Philippines",reviewed,...,",us7000ret3,",",us,",earthquake,Philippines,2025,12,1,Monday,shallow,moderate
124956,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,"78 km SW of Challapata, Bolivia",reviewed,...,",us7000ret2,",",us,",earthquake,Bolivia,2025,12,1,Monday,deep,moderate
124957,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,"27 km NE of Seeley Lake, Montana",reviewed,...,",us7000resz,",",us,",earthquake,Montana,2025,12,1,Monday,shallow,moderate
124958,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,"19 km WSW of Urakawa, Japan",reviewed,...,",us7000resx,",",us,",earthquake,Japan,2025,12,1,Monday,shallow,moderate

In [8]:
import pandas as pd
pd.read_csv("earthquake_data.csv")

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,gap,magError,depthError,magNst,locationSource,magSource,types,ids,sources,type
0,pr2020031037,2020-01-31 23:42:29.870,2020-04-18 22:10:07.040,18.8990,-67.8238,10.000,3.2,md,"70 km ENE of Punta Cana, Dominican Republic",reviewed,...,321.0,NaN,NaN,NaN,NaN,NaN,",dyfi,origin,phase-data,",",pr2020031037,us60007lv7,",",pr,us,",earthquake
1,us60007lub,2020-01-31 23:32:51.609,2020-04-18 22:10:07.040,38.4961,39.3382,10.000,4.7,mwr,"6 km NNE of Sivrice, Turkey",reviewed,...,34.0,NaN,NaN,NaN,NaN,NaN,",moment-tensor,origin,phase-data,",",us60007lub,",",us,",earthquake
2,us60007lul,2020-01-31 23:06:11.255,2020-04-18 22:10:07.040,-12.2747,-76.6148,75.510,4.7,mb,"21 km ENE of San Bartolo, Peru",reviewed,...,167.0,NaN,NaN,NaN,NaN,NaN,",dyfi,origin,phase-data,",",us60007lul,",",us,",earthquake
3,us60007lsc,2020-01-31 22:10:55.844,2025-12-22 18:27:38.231,-6.4065,129.1523,221.390,5.0,mww,Banda Sea,reviewed,...,28.0,NaN,NaN,NaN,NaN,NaN,",dyfi,moment-tensor,origin,phase-data,",",us60007lsc,iscgem617252948,",",us,iscgem,",earthquake
4,us60007lq0,2020-01-31 21:05:32.436,2020-04-18 22:10:06.040,41.4433,19.4321,10.000,4.4,mb,"13 km N of Durrës, Albania",reviewed,...,51.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us60007lq0,",",us,",earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124954,ak2025xpgfse,2025-12-01 01:51:06.974,2026-02-25 16:18:40.040,59.1380,-150.6400,15.200,3.2,ml,"60 km SSE of Halibut Cove, Alaska",reviewed,...,149.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000ret4,ak2025xpgfse,",",us,ak,",earthquake
124955,us7000ret3,2025-12-01 01:41:43.796,2026-02-25 16:18:40.040,7.4127,127.0704,35.000,4.6,mb,"53 km E of Baculin, Philippines",reviewed,...,96.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000ret3,",",us,",earthquake
124956,us7000ret2,2025-12-01 01:37:57.834,2026-02-25 16:18:40.040,-19.4176,-67.2761,227.844,4.1,mb,"78 km SW of Challapata, Bolivia",reviewed,...,95.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000ret2,",",us,",earthquake
124957,us7000resz,2025-12-01 01:25:46.725,2026-02-25 16:18:40.040,47.3283,-113.2019,30.159,3.1,ml,"27 km NE of Seeley Lake, Montana",reviewed,...,45.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000resz,",",us,",earthquake
124958,us7000resx,2025-12-01 00:48:01.683,2026-02-25 16:18:40.040,42.0602,142.5913,57.662,4.6,mb,"19 km WSW of Urakawa, Japan",reviewed,...,83.0,NaN,NaN,NaN,NaN,NaN,",origin,phase-data,",",us7000resx,",",us,",earthquake

In [11]:
print(df.dtypes)

NameError: name 'df' is not defined

In [12]:
print(df[numeric_cols].head())

NameError: name 'df' is not defined

In [13]:
print(df)

NameError: name 'df' is not defined

In [14]:
single_index = pd.pivot_table(data=df, index=['year'], values=['mag'])

NameError: name 'df' is not defined

In [ ]:
single_index

In [ ]:
single_index.plot(kind ='bar')

In [ ]:
pivot_table = pd.pivot_table(data=df, index=['country'], values=['mag'])

In [ ]:
pivot_table

In [ ]:
pivot_table.plot(kind ='bar')

In [ ]:
pivot_table = pd.pivot_table(data=df, index=['year'], values=['mag'], aggfunc='count')

In [ ]:
pivot_table

In [ ]:
pivot_table.plot(kind ='bar')

In [ ]:
single_index = pd.pivot_table(data=df, index=['year'], values=['depth_km'])

In [ ]:
single_index

In [ ]:
single_index.plot(kind ='bar')

In [ ]:
import matplotlib.pyplot as plt

yearly.plot(kind='bar', title="Earthquakes per Year")
plt.show()

In [ ]:
import matplotlib.pyplot as plt

df['depth_km'].value_counts().plot(kind='bar', title="Depth Distribution")
plt.show()

In [33]:
import mysql.connector

conn_mysql = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Anitha99"
)
cursor_mysql = conn_mysql.cursor()
print("MySQL connection established!")

MySQL connection established!

In [34]:
cursor_mysql.execute("CREATE DATABASE IF NOT EXISTS Earthquake_Project;")
print("MySQL database 'Earthquake_Project' created successfully!")

MySQL database 'Earthquake_Project' created successfully!

In [35]:
# Select Earthquake Database
cursor_mysql.execute("USE earthquake_project;")

# Create Earthquakes Table
cursor_mysql.execute("""
CREATE TABLE IF NOT EXISTS earthquakes (

    id VARCHAR(50),
    time DATETIME,
    updated DATETIME,

    latitude FLOAT,
    longitude FLOAT,
    depth_km FLOAT,

    mag FLOAT,
    magType VARCHAR(20),

    place VARCHAR(255),
    status VARCHAR(20),

    tsunami INT,
    sig INT,

    net VARCHAR(20),
    nst FLOAT,
    dmin FLOAT,
    rms FLOAT,
    gap FLOAT,

    magError FLOAT,
    depthError FLOAT,
    magNst FLOAT,

    locationSource VARCHAR(50),
    magSource VARCHAR(50),

    types TEXT,
    ids TEXT,
    sources TEXT,

    type VARCHAR(50),

    country VARCHAR(100),

    year INT,
    month INT,
    day INT,

    day_of_week VARCHAR(20),

    depth_category VARCHAR(20),
    magnitude_category VARCHAR(20)

);
""")

conn_mysql.commit()

print("Table 'earthquakes' created successfully in MySQL!")

Table 'earthquakes' created successfully in MySQL!

pip install pymysql sqlalchemy

In [36]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [37]:
import pymysql

In [38]:
myconnection = pymysql.connect(host = '127.0.0.1',user='root',passwd='Anitha99')

In [39]:
cur = myconnection.cursor()

In [40]:
cur.execute("CREATE DATABASE IF NOT EXISTS earthquakes;")

1

In [41]:
cur.execute("use Earthquake_Project")

0

In [44]:
import pandas as pd
from sqlalchemy import create_engine

# Create MySQL connection
engine = create_engine(
    "mysql+pymysql://root:Anitha99@localhost/Earthquake_Project"
)

# Store DataFrame into MySQL table
df.to_sql(
    name="earthquakes",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data stored successfully in MySQL")

Data stored successfully in MySQL

In [ ]:
import sqlite3

conn = sqlite3.connect("earthquake_database.sqlite")
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

conn.close()

In [ ]:
[]

In [ ]:
import pymysql
import pandas as pd
import numpy as np

# -------------------------------
# Connect to MySQL
# -------------------------------
connection = pymysql.connect(
    host="localhost",
    user="root",
    password="Anitha99",
    database="Earthquake_Project",
    cursorclass=pymysql.cursors.DictCursor
)

cursor = connection.cursor()

print("Connected to MySQL successfully!")

# -------------------------------
# Create Table
# -------------------------------
create_table = """
CREATE TABLE IF NOT EXISTS earthquakes (

    id VARCHAR(50),
    time DATETIME,
    updated DATETIME,

    latitude FLOAT,
    longitude FLOAT,
    depth_km FLOAT,

    mag FLOAT,
    magType VARCHAR(20),

    place VARCHAR(255),
    status VARCHAR(20),

    tsunami INT,
    sig INT,

    net VARCHAR(20),
    nst FLOAT,
    dmin FLOAT,
    rms FLOAT,
    gap FLOAT,

    magError FLOAT,
    depthError FLOAT,
    magNst FLOAT,

    locationSource VARCHAR(50),
    magSource VARCHAR(50),

    types TEXT,
    ids TEXT,
    sources TEXT,

    type VARCHAR(50),

    country VARCHAR(100),

    year INT,
    month INT,
    day INT,

    day_of_week VARCHAR(20),

    depth_category VARCHAR(20),
    magnitude_category VARCHAR(20)

)
"""

cursor.execute(create_table)

print("Table created successfully!")

# -------------------------------
# Replace NaN with None
# -------------------------------
df = df.replace({np.nan: None})

# -------------------------------
# Insert Query
# -------------------------------
insert_query = """
INSERT INTO earthquakes (

    id,
    time,
    updated,
    latitude,
    longitude,
    depth_km,
    mag,
    magType,
    place,
    status,
    tsunami,
    sig,
    net,
    nst,
    dmin,
    rms,
    gap,
    magError,
    depthError,
    magNst,
    locationSource,
    magSource,
    types,
    ids,
    sources,
    type,
    country,
    year,
    month,
    day,
    day_of_week,
    depth_category,
    magnitude_category

)

VALUES (

    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s, %s,
    %s, %s, %s

)
"""

# -------------------------------
# Insert Data
# -------------------------------
for row in df.itertuples(index=False, name=None):

    cursor.execute(insert_query, row)

# -------------------------------
# Commit Changes
# -------------------------------
connection.commit()

print("Data inserted successfully!")

# -------------------------------
# Close Connection
# -------------------------------
cursor.close()
connection.close()

print("Connection closed!")

In [48]:
print(df)

                  id                    time                 updated  \
0       pr2020031037 2020-01-31 23:42:29.870 2020-04-18 22:10:07.040
1         us60007lub 2020-01-31 23:32:51.609 2020-04-18 22:10:07.040
2         us60007lul 2020-01-31 23:06:11.255 2020-04-18 22:10:07.040
3         us60007lsc 2020-01-31 22:10:55.844 2025-12-22 18:27:38.231
4         us60007lq0 2020-01-31 21:05:32.436 2020-04-18 22:10:06.040
...              ...                     ...                     ...
124954  ak2025xpgfse 2025-12-01 01:51:06.974 2026-02-25 16:18:40.040
124955    us7000ret3 2025-12-01 01:41:43.796 2026-02-25 16:18:40.040
124956    us7000ret2 2025-12-01 01:37:57.834 2026-02-25 16:18:40.040
124957    us7000resz 2025-12-01 01:25:46.725 2026-02-25 16:18:40.040
124958    us7000resx 2025-12-01 00:48:01.683 2026-02-25 16:18:40.040

        latitude  longitude  depth_km  mag magType  \
0        18.8990   -67.8238    10.000  3.2      md
1        38.4961    39.3382    10.000  4.7     mwr
2       -12.2747   -76.6148    75.510  4.7      mb
3        -6.4065   129.1523   221.390  5.0     mww
4        41.4433    19.4321    10.000  4.4      mb
...          ...        ...       ...  ...     ...
124954   59.1380  -150.6400    15.200  3.2      ml
124955    7.4127   127.0704    35.000  4.6      mb
124956  -19.4176   -67.2761   227.844  4.1      mb
124957   47.3283  -113.2019    30.159  3.1      ml
124958   42.0602   142.5913    57.662  4.6      mb

                                              place    status  ...  \
0       70 km ENE of Punta Cana, Dominican Republic  reviewed  ...
1                       6 km NNE of Sivrice, Turkey  reviewed  ...
2                    21 km ENE of San Bartolo, Peru  reviewed  ...
3                                         Banda Sea  reviewed  ...
4                        13 km N of Durrës, Albania  reviewed  ...
...                                             ...       ...  ...
124954            60 km SSE of Halibut Cove, Alaska  reviewed  ...
124955              53 km E of Baculin, Philippines  reviewed  ...
124956              78 km SW of Challapata, Bolivia  reviewed  ...
124957             27 km NE of Seeley Lake, Montana  reviewed  ...
124958                  19 km WSW of Urakawa, Japan  reviewed  ...

                                 ids      sources        type  \
0          ,pr2020031037,us60007lv7,      ,pr,us,  earthquake
1                       ,us60007lub,         ,us,  earthquake
2                       ,us60007lul,         ,us,  earthquake
3       ,us60007lsc,iscgem617252948,  ,us,iscgem,  earthquake
4                       ,us60007lq0,         ,us,  earthquake
...                              ...          ...         ...
124954     ,us7000ret4,ak2025xpgfse,      ,us,ak,  earthquake
124955                  ,us7000ret3,         ,us,  earthquake
124956                  ,us7000ret2,         ,us,  earthquake
124957                  ,us7000resz,         ,us,  earthquake
124958                  ,us7000resx,         ,us,  earthquake

                   country  year  month  day day_of_week depth_category  \
0       Dominican Republic  2020      1   31      Friday        shallow
1                   Turkey  2020      1   31      Friday        shallow
2                     Peru  2020      1   31      Friday           deep
3                     None  2020      1   31      Friday           deep
4                  Albania  2020      1   31      Friday        shallow
...                    ...   ...    ...  ...         ...            ...
124954              Alaska  2025     12    1      Monday        shallow
124955         Philippines  2025     12    1      Monday        shallow
124956             Bolivia  2025     12    1      Monday           deep
124957             Montana  2025     12    1      Monday        shallow
124958               Japan  2025     12    1      Monday        shallow

       magnitude_category
0                moderate
1                moderate
2                moderate
3                  strong
4                moderate
...                   ...
124954           moderate
124955           moderate
124956           moderate
124957           moderate
124958           moderate

[124959 rows x 33 columns]

In [49]:
print(df.shape)

(124959, 33)

In [70]:
import pandas as pd
from sqlalchemy import create_engine

# Create MySQL connection
engine = create_engine(
    "mysql+pymysql://root:Anitha99@localhost/Earthquake_Project"
)

# Store DataFrame into MySQL table
df.to_sql(
    name="earthquakes",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data stored successfully in MySQL")

Data stored successfully in MySQL

In [3]:
%%writefile app.py

import streamlit as st

# ---------------------------------------------------
# PAGE CONFIG (MUST BE FIRST STREAMLIT COMMAND)
# ---------------------------------------------------
st.set_page_config(
    page_title="Earthquake Data Analysis",
    layout="wide"
)

import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt

# ---------------------------------------------------
# DATABASE CONNECTION
# ---------------------------------------------------
@st.cache_resource
def get_engine():
    return create_engine(
        "mysql+pymysql://root:Anitha99@localhost/Earthquake_Project"
    )

engine = get_engine()


def get_data(query, params=None):
    return pd.read_sql(query, engine, params=params)


# ---------------------------------------------------
# SIDEBAR
# ---------------------------------------------------
st.sidebar.title("🌍 Navigation")

page = st.sidebar.radio(
    "Go To",
    (
        "Project Introduction",
        "Earthquake Visualization",
        "SQL Analysis",
        "Creator Info"
    )
)

# ===================================================
# PAGE 1
# ===================================================
if page == "Project Introduction":

    st.title("🌍 Earthquake Data Analysis Dashboard")

    st.markdown("""
This dashboard analyzes earthquake data stored in MySQL.

### Features

- Earthquake filtering
- Magnitude analysis
- Depth analysis
- Location Map
- SQL Insights
- Download filtered dataset
""")

# ===================================================
# PAGE 2
# ===================================================
elif page == "Earthquake Visualization":

    st.title("🌍 Earthquake Visualization")

    min_mag = st.slider(
        "Minimum Magnitude",
        0.0,
        10.0,
        2.5
    )

    max_mag = st.slider(
        "Maximum Magnitude",
        0.0,
        10.0,
        7.0
    )

    start_date = st.date_input("Start Date")
    end_date = st.date_input("End Date")

    place_search = st.text_input("Search Place")

    query = """
    SELECT *
    FROM earthquakes
    WHERE mag BETWEEN %s AND %s
      AND DATE(time) BETWEEN %s AND %s
      AND place LIKE %s
    ORDER BY time DESC
    """
    df = get_data(
        query,
        (
            min_mag,
            max_mag,
            start_date,
            end_date,
            f"%{place_search}%"
        )
    )

    if not df.empty:

        df["time"] = pd.to_datetime(df["time"])

        df = df.dropna(
            subset=[
                "latitude",
                "longitude",
                "mag",
                "depth"
            ]
        )

        st.subheader("Filtered Data")

        st.dataframe(
            df,
            use_container_width=True
        )

        csv = df.to_csv(index=False).encode("utf-8")

        st.download_button(
            "⬇ Download CSV",
            csv,
            "earthquakes.csv",
            "text/csv"
        )

        st.subheader("Earthquake Locations")

        st.map(df[["latitude", "longitude"]])

        # Magnitude Trend
        st.subheader("Magnitude Trend")

        fig, ax = plt.subplots()

        ax.plot(
            df["time"],
            df["mag"]
        )

        ax.set_xlabel("Time")
        ax.set_ylabel("Magnitude")

        plt.xticks(rotation=45)

        st.pyplot(fig)

        # Scatter Plot
        st.subheader("Depth vs Magnitude")

        fig2, ax2 = plt.subplots()

        ax2.scatter(
            df["depth"],
            df["mag"]
        )

        ax2.set_xlabel("Depth")
        ax2.set_ylabel("Magnitude")

        st.pyplot(fig2)

        # Metrics
        col1, col2, col3 = st.columns(3)

        col1.metric(
            "Total Records",
            len(df)
        )

        col2.metric(
            "Maximum Magnitude",
            round(df["mag"].max(), 2)
        )

        col3.metric(
            "Average Depth",
            round(df["depth"].mean(), 2)
        )

        # Top 10
        st.subheader("Top 10 Strongest Earthquakes")

        top10 = get_data("""
            SELECT place, mag
            FROM earthquakes
            ORDER BY mag DESC
            LIMIT 10
        """)

        st.dataframe(top10)

        st.bar_chart(
            top10.set_index("place")
        )

    else:
        st.warning("No earthquake data found.")

# ===================================================
# PAGE 3
# ===================================================
elif page == "SQL Analysis":

    st.title("📊 SQL Analysis")

    queries = {

        "Top 10 Strongest Earthquakes":
        """
        SELECT place, mag
        FROM earthquakes
        ORDER BY mag DESC
        LIMIT 10
        """,

        "Top 10 Deepest Earthquakes":
        """
        SELECT place, depth
        FROM earthquakes
        ORDER BY depth DESC
        LIMIT 10
        """,

        "Average Magnitude by Magnitude Type":
        """
        SELECT magType,
               AVG(mag) AS Average_Magnitude
        FROM earthquakes
        GROUP BY magType
        """,

        "Earthquakes Per Hour":
        """
        SELECT HOUR(time) AS Hour,
               COUNT(*) AS Total
        FROM earthquakes
        GROUP BY HOUR(time)
        ORDER BY Hour
        """,

        "Status Count":
        """
        SELECT status,
               COUNT(*) AS Total
        FROM earthquakes
        GROUP BY status
        """
    }

    selected_query = st.selectbox(
        "Choose SQL Query",
        list(queries.keys())
    )

    result = get_data(
        queries[selected_query]
    )

    st.dataframe(
        result,
        use_container_width=True
    )

# ===================================================
# PAGE 4
# ===================================================
elif page == "Creator Info":

    st.title("👩‍💻 Creator")

    st.write("""
### Developed By

**Name:** Vinodhini

### Skills

- Python
- SQL
- Streamlit
- Data Analysis
""")

    st.image(
        "https://via.placeholder.com/150",
        width=150
    )

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------
st.markdown("---")
st.caption("Earthquake Data Analysis Dashboard")

Overwriting app.py

In [ ]:
import os
import streamlit as st
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------------------------------
# PAGE CONFIG
# -------------------------------------------------
st.set_page_config(
    page_title="Earthquake Data Analysis",
    layout="wide"
)

# -------------------------------------------------
# DATABASE CONNECTION
# -------------------------------------------------
@st.cache_resource
def get_engine():
    return create_engine(
        "mysql+pymysql://root:Anitha99@localhost/Earthquake_Project"
    )

try:
    engine = get_engine()
except Exception as e:
    st.error(f"Database Connection Failed\n\n{e}")
    st.stop()


def get_data(query, params=None):
    return pd.read_sql(query, engine, params=params)


# -------------------------------------------------
# SIDEBAR
# -------------------------------------------------
st.sidebar.title("🌍 Navigation")

page = st.sidebar.radio(
    "Go to",
    [
        "Project Introduction",
        "Earthquake Visualization",
        "SQL Queries",
        "Creator Info"
    ]
)

# ==========================================================
# PAGE 1
# ==========================================================
if page == "Project Introduction":

    st.title("🌍 Earthquake Data Analysis Dashboard")

    st.markdown("""
This project analyzes global earthquake data stored in **MySQL**
using **Python**, **Pandas**, **SQLAlchemy**, and **Streamlit**.

### Features

- Earthquake filtering
- Interactive visualizations
- Earthquake location map
- SQL analysis
- Dashboard reports
""")

    image_path = "images/earthquake_banner.jpg"

    if os.path.exists(image_path):
        st.image(image_path, use_container_width=True)
    else:
        st.warning(
            "Image not found.\nPlace earthquake_banner.jpg inside the images folder."
        )

# ==========================================================
# PAGE 2
# ==========================================================
elif page == "Earthquake Visualization":

    st.title("📊 Earthquake Visualization")

    col1, col2 = st.columns(2)

    with col1:
        min_mag = st.slider(
            "Minimum Magnitude",
            0.0,
            10.0,
            2.5
        )

    with col2:
        max_mag = st.slider(
            "Maximum Magnitude",
            0.0,
            10.0,
            7.0
        )

    col3, col4 = st.columns(2)

    with col3:
        start_date = st.date_input("Start Date")

    with col4:
        end_date = st.date_input("End Date")

    if start_date > end_date:
        st.error("Start Date must be before End Date.")
        st.stop()

    query = """
    SELECT *
    FROM earthquakes
    WHERE mag BETWEEN %s AND %s
      AND DATE(time) BETWEEN %s AND %s
    ORDER BY time DESC
    """

    try:
        df = get_data(
            query,
            params=(
                min_mag,
                max_mag,
                start_date,
                end_date
            )
        )

    except Exception as e:
        st.error(e)
        st.stop()

    if df.empty:
        st.warning("No earthquake records found.")
    else:

        df["time"] = pd.to_datetime(df["time"])

        df = df.dropna(
            subset=[
                "latitude",
                "longitude",
                "mag",
                "depth"
            ]
        )

        st.subheader("Filtered Earthquake Records")

        st.dataframe(
            df,
            use_container_width=True
        )

        st.subheader("Earthquake Locations")

        st.map(
            df[["latitude", "longitude"]]
        )

        st.subheader("Magnitude Trend")

        fig1, ax1 = plt.subplots(figsize=(10,4))

        sns.lineplot(
            data=df,
            x="time",
            y="mag",
            ax=ax1
        )

        ax1.set_xlabel("Time")
        ax1.set_ylabel("Magnitude")
        ax1.set_title("Magnitude Over Time")

        fig1.autofmt_xdate()

        st.pyplot(fig1)

        st.subheader("Depth vs Magnitude")

        fig2, ax2 = plt.subplots(figsize=(8,5))

        sns.scatterplot(
            data=df,
            x="depth",
            y="mag",
            ax=ax2
        )

        ax2.set_xlabel("Depth")
        ax2.set_ylabel("Magnitude")
        ax2.set_title("Depth vs Magnitude")

        st.pyplot(fig2)

# ==========================================================
# PAGE 3
# ==========================================================
elif page == "SQL Queries":

    st.title("📋 SQL Query Results")

    queries = {

        "Top 10 Strongest Earthquakes":
        """
        SELECT place, mag
        FROM earthquakes
        ORDER BY mag DESC
        LIMIT 10
        """,

        "Top 10 Deepest Earthquakes":
        """
        SELECT place, depth
        FROM earthquakes
        ORDER BY depth DESC
        LIMIT 10
        """,

        "Average Magnitude by Type":
        """
        SELECT magType,
               ROUND(AVG(mag),2) AS Average_Magnitude
        FROM earthquakes
        GROUP BY magType
        ORDER BY Average_Magnitude DESC
        """,

        "Earthquakes per Hour":
        """
        SELECT HOUR(time) AS Hour,
               COUNT(*) AS Total
        FROM earthquakes
        GROUP BY HOUR(time)
        ORDER BY Hour
        """,

        "Status Count":
        """
        SELECT status,
               COUNT(*) AS Total
        FROM earthquakes
        GROUP BY status
        ORDER BY Total DESC
        """
    }

    selected_query = st.selectbox(
        "Choose SQL Query",
        list(queries.keys())
    )

    result = get_data(
        queries[selected_query]
    )

    st.dataframe(
        result,
        use_container_width=True
    )

# ==========================================================
# PAGE 4
# ==========================================================
elif page == "Creator Info":

    st.title("👩‍💻 Creator Information")

    st.markdown("""
## Developed By

**Vinodhini**

### Skills

- Python
- SQL
- Streamlit
- Pandas
- Data Analysis
- Data Visualization

### Project

Earthquake Data Analysis using MySQL and Streamlit.
""")

    st.image(
        "https://via.placeholder.com/200",
        width=200
    )

In [ ]:
!pip install streamlit

In [ ]:
#!streamlit run app.py

In [ ]:
streamlit run app.py